import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    dashboard: 'Dashboard',
    employees: 'Employees',
    inventory: 'Inventory',
    sales: 'Sales',
    customers: 'Customers',
    projects: 'Projects',
    finance: 'Finance',
    attendance: 'Attendance',
    calendar: 'Calendar',
    profile: 'Profile',
    admin: 'Admin',
    login: 'Login',
    logout: 'Logout',
    search: 'Search',
    export: 'Export',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    noData: 'No data available',
    totalEmployees: 'Total Employees',
    totalProducts: 'Total Products',
    totalSales: 'Total Sales',
    totalRevenue: 'Total Revenue',
    salesRevenueTrend: 'Sales & Revenue Trend',
    departmentDistribution: 'Department Distribution',
    inventoryStatus: 'Inventory Status',
    monthlyRevenue: 'Monthly Revenue',
    recentActivity: 'Recent Activity',
    settings: 'Settings',
    management: 'Management',
    name: 'Name',
    email: 'Email',
    department: 'Department',
    position: 'Position',
    status: 'Status',
    actions: 'Actions',
    view: 'View',
    create: 'Create',
    update: 'Update',
    inventoryManagement: 'Inventory Management',
    salesManagement: 'Sales Management',
    customerManagement: 'Customer Management',
    projectManagement: 'Project Management',
    financeManagement: 'Finance Management',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone',
    company: 'Company',
    price: 'Price',
    quantity: 'Quantity',
    total: 'Total',
    date: 'Date',
    description: 'Description',
    humanResourceManagement: 'Human Resource Management',
    leaveManagement: 'Leave Management',
    trainingDevelopment: 'Training & Development',
    performanceReviews: 'Performance Reviews',
    payrollManagement: 'Payroll Management',
    departmentManagement: 'Department Management',
    stockMovements: 'Stock Movements',
    supplierManagement: 'Supplier Management',
    categoryManagement: 'Category Management',
    warehouseManagement: 'Warehouse Management',
    leadManagement: 'Lead Management',
    quoteManagement: 'Quote Management',
    orderManagement: 'Order Management',
    invoiceManagement: 'Invoice Management',
    salesOrders: 'Sales Orders',
    salesPipeline: 'Sales Pipeline',
    addNew: 'Add New',
    editItem: 'Edit',
    deleteItem: 'Delete',
    viewDetails: 'View Details',
    searchPlaceholder: 'Search...',
    noDataFound: 'No data found',
    loadingData: 'Loading data...',
    saveChanges: 'Save Changes',
    cancelAction: 'Cancel',
    confirmAction: 'Confirm',
    active: 'Active',
    inactive: 'Inactive',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    completed: 'Completed',
    inProgress: 'In Progress',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    employeeId: 'Employee ID',
    productId: 'Product ID',
    orderId: 'Order ID',
    invoiceId: 'Invoice ID',
    startDate: 'Start Date',
    endDate: 'End Date',
    dueDate: 'Due Date',
    createdDate: 'Created Date',
    lastModified: 'Last Modified',
    analytics: 'Analytics',
    reports: 'Reports',
    exportData: 'Export Data',
    importData: 'Import Data',
    leadPipelineStatus: 'Lead Pipeline Status',
    projectStatusDistribution: 'Project Status Distribution',
    projectStatus: 'Project Status',
    leadPipeline: 'Lead Pipeline',
    todaysAttendance: "Today's Attendance",
    present: 'Present',
    late: 'Late',
    upcomingEvents: 'Upcoming Events',
    stockAlerts: 'Stock Alerts',
    lowStock: 'Low Stock',
    quickStats: 'Quick Stats',
    events: 'Events',
    alerts: 'Alerts',
    allStockGood: 'All stock levels good',
    noLowStockAlerts: 'No low stock alerts'
  },
  es: {
    dashboard: 'Panel de Control',
    employees: 'Empleados',
    inventory: 'Inventario',
    sales: 'Ventas',
    customers: 'Clientes',
    projects: 'Proyectos',
    finance: 'Finanzas',
    attendance: 'Asistencia',
    calendar: 'Calendario',
    profile: 'Perfil',
    admin: 'Administrador',
    login: 'Iniciar Sesión',
    logout: 'Cerrar Sesión',
    search: 'Buscar',
    export: 'Exportar',
    add: 'Agregar',
    edit: 'Editar',
    delete: 'Eliminar',
    save: 'Guardar',
    cancel: 'Cancelar',
    loading: 'Cargando...',
    noData: 'No hay datos disponibles',
    totalEmployees: 'Total Empleados',
    totalProducts: 'Total Productos',
    totalSales: 'Total Ventas',
    totalRevenue: 'Ingresos Totales',
    salesRevenueTrend: 'Tendencia de Ventas e Ingresos',
    departmentDistribution: 'Distribución por Departamento',
    inventoryStatus: 'Estado del Inventario',
    monthlyRevenue: 'Ingresos Mensuales',
    recentActivity: 'Actividad Reciente',
    settings: 'Configuración',
    management: 'Gestión',
    name: 'Nombre',
    email: 'Correo',
    department: 'Departamento',
    position: 'Posición',
    status: 'Estado',
    actions: 'Acciones',
    view: 'Ver',
    create: 'Crear',
    update: 'Actualizar',
    inventoryManagement: 'Gestión de Inventario',
    salesManagement: 'Gestión de Ventas',
    customerManagement: 'Gestión de Clientes',
    projectManagement: 'Gestión de Proyectos',
    financeManagement: 'Gestión Financiera',
    firstName: 'Nombre',
    lastName: 'Apellido',
    phone: 'Teléfono',
    company: 'Empresa',
    price: 'Precio',
    quantity: 'Cantidad',
    total: 'Total',
    date: 'Fecha',
    description: 'Descripción',
    humanResourceManagement: 'Gestión de Recursos Humanos',
    leaveManagement: 'Gestión de Permisos',
    trainingDevelopment: 'Formación y Desarrollo',
    performanceReviews: 'Evaluaciones de Desempeño',
    payrollManagement: 'Gestión de Nómina',
    departmentManagement: 'Gestión de Departamentos',
    stockMovements: 'Movimientos de Stock',
    supplierManagement: 'Gestión de Proveedores',
    categoryManagement: 'Gestión de Categorías',
    warehouseManagement: 'Gestión de Almacenes',
    leadManagement: 'Gestión de Prospectos',
    quoteManagement: 'Gestión de Cotizaciones',
    orderManagement: 'Gestión de Pedidos',
    invoiceManagement: 'Gestión de Facturas',
    salesOrders: 'Pedidos de Venta',
    salesPipeline: 'Pipeline de Ventas',
    addNew: 'Agregar Nuevo',
    editItem: 'Editar',
    deleteItem: 'Eliminar',
    viewDetails: 'Ver Detalles',
    searchPlaceholder: 'Buscar...',
    noDataFound: 'No se encontraron datos',
    loadingData: 'Cargando datos...',
    saveChanges: 'Guardar Cambios',
    cancelAction: 'Cancelar',
    confirmAction: 'Confirmar',
    active: 'Activo',
    inactive: 'Inactivo',
    pending: 'Pendiente',
    approved: 'Aprobado',
    rejected: 'Rechazado',
    completed: 'Completado',
    inProgress: 'En Progreso',
    high: 'Alto',
    medium: 'Medio',
    low: 'Bajo',
    employeeId: 'ID Empleado',
    productId: 'ID Producto',
    orderId: 'ID Pedido',
    invoiceId: 'ID Factura',
    startDate: 'Fecha Inicio',
    endDate: 'Fecha Fin',
    dueDate: 'Fecha Vencimiento',
    createdDate: 'Fecha Creación',
    lastModified: 'Última Modificación',
    analytics: 'Análisis',
    reports: 'Reportes',
    exportData: 'Exportar Datos',
    importData: 'Importar Datos',
    leadPipelineStatus: 'Estado del Pipeline de Leads',
    projectStatusDistribution: 'Distribución de Estado de Proyectos',
    projectStatus: 'Estado del Proyecto',
    leadPipeline: 'Pipeline de Leads',
    todaysAttendance: 'Asistencia de Hoy',
    present: 'Presente',
    late: 'Tarde',
    upcomingEvents: 'Próximos Eventos',
    stockAlerts: 'Alertas de Stock',
    lowStock: 'Stock Bajo',
    quickStats: 'Estadísticas Rápidas',
    events: 'Eventos',
    alerts: 'Alertas',
    allStockGood: 'Todos los niveles de stock buenos',
    noLowStockAlerts: 'No hay alertas de stock bajo'
  },
  fr: {
    dashboard: 'Tableau de Bord',
    employees: 'Employés',
    inventory: 'Inventaire',
    sales: 'Ventes',
    customers: 'Clients',
    projects: 'Projets',
    finance: 'Finance',
    attendance: 'Présence',
    calendar: 'Calendrier',
    profile: 'Profil',
    admin: 'Administrateur',
    login: 'Se Connecter',
    logout: 'Se Déconnecter',
    search: 'Rechercher',
    export: 'Exporter',
    add: 'Ajouter',
    edit: 'Modifier',
    delete: 'Supprimer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    loading: 'Chargement...',
    noData: 'Aucune donnée disponible',
    totalEmployees: 'Total Employés',
    totalProducts: 'Total Produits',
    totalSales: 'Total Ventes',
    totalRevenue: 'Revenus Totaux',
    salesRevenueTrend: 'Tendance Ventes et Revenus',
    departmentDistribution: 'Distribution par Département',
    inventoryStatus: 'Statut Inventaire',
    monthlyRevenue: 'Revenus Mensuels',
    recentActivity: 'Activité Récente',
    settings: 'Paramètres',
    management: 'Gestion',
    name: 'Nom',
    email: 'Email',
    department: 'Département',
    position: 'Position',
    status: 'Statut',
    actions: 'Actions',
    view: 'Voir',
    create: 'Créer',
    update: 'Mettre à jour',
    inventoryManagement: 'Gestion Inventaire',
    salesManagement: 'Gestion des Ventes',
    customerManagement: 'Gestion Clients',
    projectManagement: 'Gestion Projets',
    financeManagement: 'Gestion Financière',
    firstName: 'Prénom',
    lastName: 'Nom',
    phone: 'Téléphone',
    company: 'Entreprise',
    price: 'Prix',
    quantity: 'Quantité',
    total: 'Total',
    date: 'Date',
    description: 'Description',
    humanResourceManagement: 'Gestion des Ressources Humaines',
    leaveManagement: 'Gestion des Congés',
    trainingDevelopment: 'Formation et Développement',
    performanceReviews: 'Évaluations de Performance',
    payrollManagement: 'Gestion de la Paie',
    departmentManagement: 'Gestion des Départements',
    stockMovements: 'Mouvements de Stock',
    supplierManagement: 'Gestion des Fournisseurs',
    categoryManagement: 'Gestion des Catégories',
    warehouseManagement: 'Gestion des Entrepôts',
    leadManagement: 'Gestion des Prospects',
    quoteManagement: 'Gestion des Devis',
    orderManagement: 'Gestion des Commandes',
    invoiceManagement: 'Gestion des Factures',
    salesOrders: 'Commandes de Vente',
    salesPipeline: 'Pipeline de Vente',
    addNew: 'Ajouter Nouveau',
    editItem: 'Modifier',
    deleteItem: 'Supprimer',
    viewDetails: 'Voir Détails',
    searchPlaceholder: 'Rechercher...',
    noDataFound: 'Aucune donnée trouvée',
    loadingData: 'Chargement des données...',
    saveChanges: 'Enregistrer',
    cancelAction: 'Annuler',
    confirmAction: 'Confirmer',
    active: 'Actif',
    inactive: 'Inactif',
    pending: 'En Attente',
    approved: 'Approuvé',
    rejected: 'Rejeté',
    completed: 'Terminé',
    inProgress: 'En Cours',
    high: 'Haut',
    medium: 'Moyen',
    low: 'Bas',
    employeeId: 'ID Employé',
    productId: 'ID Produit',
    orderId: 'ID Commande',
    invoiceId: 'ID Facture',
    startDate: 'Date Début',
    endDate: 'Date Fin',
    dueDate: 'Date Échéance',
    createdDate: 'Date Création',
    lastModified: 'Dernière Modification',
    analytics: 'Analyses',
    reports: 'Rapports',
    exportData: 'Exporter Données',
    importData: 'Importer Données',
    leadPipelineStatus: 'Statut du Pipeline de Prospects',
    projectStatusDistribution: 'Répartition du Statut des Projets',
    projectStatus: 'Statut du Projet',
    leadPipeline: 'Pipeline de Prospects',
    todaysAttendance: "Présence d'Aujourd'hui",
    present: 'Présent',
    late: 'En Retard',
    upcomingEvents: 'Événements à Venir',
    stockAlerts: 'Alertes de Stock',
    lowStock: 'Stock Faible',
    quickStats: 'Statistiques Rapides',
    events: 'Événements',
    alerts: 'Alertes',
    allStockGood: 'Tous les niveaux de stock bons',
    noLowStockAlerts: 'Aucune alerte de stock faible'
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
      localStorage.setItem('language', lang);
    }
  };

  // Load saved language on mount
  useEffect(() => {
    const saved = localStorage.getItem('language');
    if (saved && translations[saved]) {
      setLanguage(saved);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;